name: PR check runner
description: Re-runs a check on a PR if needed
inputs:
  token:
    required: true
    description: "Token to perform api calls"
  base_branch:
    required: true
    description: "The base branch - where the PR is merged"
  pr_number:
    required: true
    description: "The PR number"
  check_name:
    required: true
    description: "The name of the check to be re-run"
  number_of_required_approves:
    required: true
    description: "The number of required approves on a PR"

runs:
  using: node16
  main: bin/index.js

branding:
  icon: git-pull-request
  color: green
